### ISSUE TITLE
check pourquoi de temps en temps on a une 500

### ISSUE THREAD

**Issue by Nydareld** [Nydareld/keycloak-user-bundle#1]

**Comment by sguesdon** [comment]
Mdr,

Je connais cette théorie !

Le mar. 5 mars 2019 à 00:35, Théo Guerin <notifications@github.com> a
écrit :

**Comment by Nydareld** [comment]
C'est dans mon code, je pense que c'est ma faute. mais en tout cas on vera demain :D ( en tout cas l'auth basique marche, de temps en temps ca 500 mais c'est utilisable )
